### ISSUE TITLE
Modais adicionais

### ISSUE THREAD

**Issue by emysdias** [UnBArqDsw2021-1/2021.1_G02_TaNaMesa_Frontend#15]
## Descrição da Issue
Fazer modal de confirmação

## Tasks:
- [ ] Fazer modal
- [ ] Fazer testes
- [ ] Fazer modal com botão que será um componente q não é pra fazer nessa branch
- [ ] Modal deve permitir ter icone ou não
- [ ] Pode copiar a estrutura do modal de login

![image](https://user-images.githubusercontent.com/52640974/133187757-6ec6d1bc-4382-472b-ae44-cc688e1417eb.png)
![image](https://user-images.githubusercontent.com/52640974/133187779-d328e114-3e61-4d7e-aa95-6b7b178de087.png)
![image](https://user-images.githubusercontent.com/52640974/133187920-06d5e658-8f91-4f4d-87b7-8fe1bb75652c.png)
