### ISSUE TITLE
Modal de pedido

### ISSUE THREAD

**Issue by emysdias** [UnBArqDsw2021-1/2021.1_G02_TaNaMesa_Frontend#16]
## Descrição da Issue
Fazer modal de pedido

## Tasks:
- [ ] Ter o passo a passo como no figma
- [ ] Não fazer checkbox pois já vai estar em outra branch
- [ ] Não fazer botão de 'proximo' mas os outros sim 'deseja'...

![image](https://user-images.githubusercontent.com/52640974/133188197-318652d5-3e47-4c06-871c-079fef4ba0d4.png)
![image](https://user-images.githubusercontent.com/52640974/133188234-45611342-5bc9-4f26-8372-41b73cdfcbb8.png)
![image](https://user-images.githubusercontent.com/52640974/133188257-426a7bd0-3696-42cf-b707-2e99efc8e58b.png)
