### ISSUE TITLE
Configurando repositório de frontend

### ISSUE THREAD

**Issue by lboaventura25** [UnBArqDsw2021-1/2021.1_G02_TaNaMesa_Frontend#2]
## Descrição da Issue
Configuração do repositório de frontend.

## Como será avaliado?
Para a valiar a issue os seguites testes serão feitos:
- Entrando dentro do código e checando as dependências que estão sendo utilizadas.

Se os testes forem bem sucedidos, a issue será considerada concluída.

## Tasks:
- [x] Criar projeto react com typescript
- [x] Adicionar .editorconfig
- [x] Adicionar eslint e prettier
- [x] Criar uma estrutura inicial de pastas.

**Comment by sergiosacj** [comment]
Marquei como duplicada porque a issue (#1) já tinha como foco isso.

Como dito nesse [comentário](https://github.com/UnBArqDsw2021-1/2021.1_G02_TaNaMesa_Frontend/pull/3#issuecomment-909756866), o foco dela é outro.

Tasks atualizadas:
- [ ] Criar estrutura inicial de pastas
- [ ] Migrar arquivos JS para TSX
