### ISSUE TITLE
Integrar parte de deletar solicitação de ajuda

### ISSUE THREAD

**Issue by emysdias** [UnBArqDsw2021-1/2021.1_G02_TaNaMesa_Frontend#43]
## Descrição da Issue
Deletar solicitações de ajuda do garçom

## Como será avaliado?
Ter solicitação deletada quando clica, e aparece modal

## Tasks:
- [ ] Aparecer modal que deletou solicitação
- [ ] Deletar solicitação de ajuda no banco
- [ ] Integrar parte de solicitação

![image](https://user-images.githubusercontent.com/52640974/136628794-0e1cbf85-8cf8-4692-99c7-29f4f19eacc3.png)
