### ISSUE TITLE
Integrar modal de comanda

### ISSUE THREAD

**Issue by ServidioEC** [UnBArqDsw2021-1/2021.1_G02_TaNaMesa_Frontend#45]
## Descrição da Issue
Adicionar e remover comandas.

## Como será avaliado?
Avaliar se é possível selecionar, adicionar e remover uma comanda do banco.

## Tasks:
- [x] Selecionar uma comanda pelo nome do cliente no banco.
- [x] Adicionar uma comanda no nome do cliente no banco.
- [x] Remover uma comanda do nome do cliente no banco.
