### ISSUE TITLE
Criar botão reutilizável

### ISSUE THREAD

**Issue by emysdias** [UnBArqDsw2021-1/2021.1_G02_TaNaMesa_Frontend#8]
## Descrição da Issue
Fazer um botão reutilizável (component), pois ele é usado em diversos lugares

## Como será avaliado?
Se ele pode ser reutilizável, se tem testes

## Tasks:
- [x] Fazer botão que pode trocar de cor
- [x] Fazer botão que pode mudar de dimensões
- [x] Fazer os testes

![image](https://user-images.githubusercontent.com/52640974/133184872-0a1df03d-4f85-43f0-9012-b692b1472115.png)
![image](https://user-images.githubusercontent.com/52640974/133184901-1beb229f-84d9-4df5-83ca-0656e58bb4a8.png)
![image](https://user-images.githubusercontent.com/52640974/133184929-136ab57b-e8a3-409d-b658-5a722a6054bb.png)
